- link:
    ~/.config/fish/config.fish: shells/fish/config.fish
    ~/.config/fish/abbr.fish: shells/fish/abbr.fish
    ~/.config/fish/functions/fisher.fish: shells/fish/functions/fisher.fish
    ~/.config/fish/completions/pass.fish: shells/fish/completions/pass.fish
    ~/.config/omf: shells/fish/omf
- shell:
    - "omf install"
