- link:
    ~/.config/fish/config.fish: shells/fish/config.fish
    ~/.config/fish/abbr.fish: shells/fish/abbr.fish
    ~/.config/fish/functions/fisher.fish: shells/fish/functions/fisher.fish
    ~/.config/fish/fishfile: shells/fish/fishfile
    ~/.config/fish/completions/pass.fish: shells/fish/completions/pass.fish
- shell:
    - "bash -c '[[ -d ~/.fzf ]] || git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf'"
    - "~/.fzf/install"
    - "fish -c 'fisher'"
