- link:
    ~/.config/fish/config.fish: shells/fish/config.fish
    ~/.config/fish/abbr.fish: shells/fish/abbr.fish
    ~/.config/fish/fish_plugins: shells/fish/fish_plugins
    ~/.config/fish/functions/fisher.fish: shells/fish/functions/fisher.fish
    ~/.config/fish/completions/fisher.fish: shells/fish/completions/fisher.fish
    ~/.config/fish/completions/pass.fish: shells/fish/completions/pass.fish
    # ~/.config/omf: shells/fish/omf
    ~/.config/fish/completions/kubectl.fish: shells/fish/fish-kubectl-completions/completions/kubectl.fish
- shell:
    - "fisher update"
    - "tide configure --auto --style=Classic --prompt_colors='True color' --classic_prompt_color=Dark --show_time='24-hour format' --classic_prompt_separators=Angled --powerline_prompt_heads=Sharp --powerline_prompt_tails=Flat --powerline_prompt_style='One line' --prompt_spacing=Compact --icons='Many icons' --transient=Yes"
