- shell:
    - "sudo add-apt-repository -u ppa:snwh/ppa"
    - "sudo apt-get install moka-icon-theme faba-icon-theme faba-mono-icons"

- link:
    ~/.config/i3: i3
    ~/.config/i3blocks/config: i3/i3blocks.conf
