- link:
    ~/.vim: editors/vim
    ~/.config/nvim: editors/vim
    ~/.vimrc: editors/vim/vimrc
    ~/.vimrc.go: editors/vim/vimrc.go
    ~/.config/nvim/init.vim: editors/vim/vimrc
- shell:
    - [vim -c 'PluginInstall' +qall, Installing vim plugins]
