#!/bin/sh

VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')
MUTED=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 1)

case "$BLOCK_BUTTON" in
  1) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
  4) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ ;;
  5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- ;;
esac

if [ "$MUTED" = "1" ]; then
  echo "🔇 ${VOL}%"
else
  echo "♪ ${VOL}%"
fi
